accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'

urlpatterns = [
    path('register/', views.SignUp.as_view(), name = 'signup')
]

pay/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('pays.urls', namespace='pays')),
    path('accounts/', include('accounts.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
]

pays/urls.py
from django.urls import path
from . import views

app_name = 'pays'

urlpatterns = [
    path('', views.index, name='index'),
    path('pagamentos/', views.pay, name='pay'),
    path('confirmar/<int:id>', views.confirmar, name='confirmar'),
    path('info/', views.info, name='info'),
    path('inscricoes/', views.inscricoes, name='inscricoes'),
    path('biblioteca/', views.biblioteca, name='biblioteca'),
    path('comentario/', views.comentario, name='comentario'),
    path('alunos/', views.alunos, name='alunos' ),
    path('horario/', views.hor, name='hor'),
    path('melhores_alunos/', views.mel, name='mel'),
    path('professores/', views.prof, name='prof')
 ]

accounts/models.py
from django.db import models

# Create your models here.

pays/models.py
from django.db import models
from django.contrib.auth import get_user_model

# Create your models here.

class Pagar(models.Model):
    nome = models.CharField('Nome do aluno', max_length=20)
    classe = models.CharField('Classe e Turma', max_length=20)
    valor = models.DecimalField(max_digits=10, decimal_places=5)
    mes = models.CharField('mês', choices=[('Janeiro', 'Janeiro'), ('Fevereiro', 'Fevereiro'),
                                           ('Março', 'Março'), ('Abril', 'Abril'), ('Maio', 'Maio'), ('Junho', 'Junho'), ('Julho', 'Julho'), ('Agosto', 'Agosto'), ('Setembro', 'Setembro'), ('Outubro', 'Outubro'), ('Novembro', 'Novembro'), ('Desembro', 'Desembro')], max_length=20)
    email = models.EmailField(max_length=50)
    user = models.ForeignKey(get_user_model(), on_delete = models.DO_NOTHING)
    def __str__(self):
        return self.nome

class Inscricoes(models.Model):
    nome = models.CharField('Nome completo', max_length=20)
    curso = models.CharField(max_length=23, choices=[('Curso de informática', 'Curso de informática'), ('Curso de medicina geral', 'Curso de medicina geral'), ('Curso de electrónica', 'Curso de electrónica'), ('Curso de artes', 'Curso de artes')])
    valor = models.DecimalField(max_digits=10, decimal_places=2, default=1000)
    numero = models.DecimalField('Número de celular', max_digits=9, decimal_places=0)
    email = models.EmailField(max_length=50)
    def __str__(self):
        return self.nome

class Comentario(models.Model):
    opiniao = models.TextField()
    data = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.opiniao

pays/forms.py
from django import forms
from .models import Pagar, Comentario, Inscricoes

class PagarForm(forms.ModelForm):

    class Meta:
        model = Pagar
        fields = ['classe', 'nome','valor', 'mes', 'email']

class InscricoesForm(forms.ModelForm):

    class Meta:
        model= Inscricoes
        fields = ['nome', 'valor', 'curso', 'email', 'numero']

class ComentarioForm(forms.ModelForm):

    class Meta:
        model= Comentario
        fields = ['opiniao']

accounts/views.py
from django.shortcuts import render
from django.contrib.auth.forms import UserCreationForm
from django.urls import reverse_lazy
from django.views import generic

class SignUp(generic.CreateView):
    form_class = UserCreationForm
    success_url = reverse_lazy('login')
    template_name = 'registration/register.html'

pays/views.py
from django.shortcuts import render
from django.shortcuts import redirect, get_object_or_404
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.contrib import messages
from django.contrib.auth.decorators import login_required

from.models import Pagar, Comentario
from .forms import PagarForm, InscricoesForm, ComentarioForm

def index(request):
    return render(request, 'pays/index.html')

@login_required
def pay(request):
    pay = Pagar.objects.filter(user=request.user)
    if request.method == 'POST':

        form = PagarForm(request.POST)
        messages.info(request, 'Mensalidade pagada com sucesso. Verifique o seu recibo na sua conta gmail')

        if form.is_valid():
            pay = form.save(commit=False)
            pay.user = request.user
            pay.save()
        return redirect('/pagamentos/')

    else:
        form = PagarForm()
        return render(request, 'pays/pay.html', {'form': form, 'pay':pay})

def confirmar(request, id):
    pagar = get_object_or_404(Pagar, pk=id)
    return render(request, 'pays/confirmar.html', {'pagar':pagar})


def info(request):
    comentario = Comentario.objects.all().order_by('-data')
    return render(request, 'pays/info.html', {'comentario': comentario})

def inscricoes(request):
    if request.method == 'POST':

        form = InscricoesForm(request.POST)

        if form.is_valid():
            form.save()
        return redirect('/info/')

    else:
        form = InscricoesForm()
        return render(request, 'pays/inscricoes.html', {'form': form})

def biblioteca(request):
    return render(request, 'pays/biblioteca.html',)

def comentario(request):
    if request.method == 'POST':

        form = ComentarioForm(request.POST)

        if form.is_valid():
            form.save()
        return redirect('/info/')

    else:
        form = ComentarioForm()
        return render(request, 'pays/comentario.html', {'form': form})


def alunos(request):
    return render(request, 'pays/alunos.html')

def hor(request):
    return render(request, 'pays/hor.html')

def mel(request):
    return render(request, 'pays/mel.html')

def prof(request):
    return render(request, 'pays/prof.html')

pays/templates/pays/alunos.html
{% extends 'pays/base.html'%}
{% load static%}

{% block content%}
<h1 class="titulo">Escola</h1>
<h2 class="titulo">Lista das Turmas para o ano 2021</h2>

<div class="offset-1 col-10">
    <a class="btn btn-primary btn-block lista" href="https://drive.google.com/file/d/1T-RPXH6MYMDmjpL7e9cTJ0MGWvJGiL6C/view?usp=sharing">1 classe</a>
    <a class="btn btn-primary btn-block lista" href="https://drive.google.com/file/d/1T-RPXH6MYMDmjpL7e9cTJ0MGWvJGiL6C/view?usp=sharing">2 classe</a>
    <a class="btn btn-primary btn-block lista" href="https://drive.google.com/file/d/1T-RPXH6MYMDmjpL7e9cTJ0MGWvJGiL6C/view?usp=sharing">3 classe</a>
    <a class="btn btn-primary btn-block lista" href="https://drive.google.com/file/d/1T-RPXH6MYMDmjpL7e9cTJ0MGWvJGiL6C/view?usp=sharing">4 classe</a>
    <a class="btn btn-primary btn-block lista" href="https://drive.google.com/file/d/1T-RPXH6MYMDmjpL7e9cTJ0MGWvJGiL6C/view?usp=sharing">5 classe</a>
    <a class="btn btn-primary btn-block lista" href="https://drive.google.com/file/d/1T-RPXH6MYMDmjpL7e9cTJ0MGWvJGiL6C/view?usp=sharing">6 classe</a>
    <a class="btn btn-primary btn-block lista" href="https://drive.google.com/file/d/1T-RPXH6MYMDmjpL7e9cTJ0MGWvJGiL6C/view?usp=sharing">7 classe</a>
    <a class="btn btn-primary btn-block lista" href="https://drive.google.com/file/d/1T-RPXH6MYMDmjpL7e9cTJ0MGWvJGiL6C/view?usp=sharing">8 classe</a>
    <a class="btn btn-primary btn-block lista" href="https://drive.google.com/file/d/1T-RPXH6MYMDmjpL7e9cTJ0MGWvJGiL6C/view?usp=sharing">9 classe</a>
    <a class="btn btn-primary btn-block lista" href="https://drive.google.com/file/d/1T-RPXH6MYMDmjpL7e9cTJ0MGWvJGiL6C/view?usp=sharing">10 classe</a>
    <a class="btn btn-primary btn-block lista" href="https://drive.google.com/file/d/1T-RPXH6MYMDmjpL7e9cTJ0MGWvJGiL6C/view?usp=sharing">11 classe</a>
    <a class="btn btn-primary btn-block lista" href="https://drive.google.com/file/d/1T-RPXH6MYMDmjpL7e9cTJ0MGWvJGiL6C/view?usp=sharing">12 classe</a>

</div>
{% endblock content%}

pays/templates/pays/base.html
{% load static%}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Escola</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-giJF6kkoqNQ00vy+HMDP7azOuL0xtbfIcaT9wjKHr8RbDVddVHyTfAAsrekwKmP1" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'css/style.css'%}">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
</head>
<body>
<div class="container-fluid">

<!---------------------------------------------------------------------------------------------------->
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container-fluid">
    <a class="navbar-brand" href="/">Escola</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNavDropdown">
      <ul class="navbar-nav">
         {% if user.is_authenticated%}
                 <!--   <li class="nav-item">
                        <a class="nav-link" href="{% url 'pays:index'%}" > Listas</a>
                    </li> -->
          <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                  Listas
              </a>
              <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                  <li><a class="dropdown-item" href="{% url 'pays:alunos'%}">dos alunos</a></li>
                  <li><a class="dropdown-item" href="{% url 'pays:hor'%}">horários</a></li>
                  <li><a class="dropdown-item" href="{% url 'pays:mel'%}">dos melhores alunos</a></li>
                  <li><a class="dropdown-item" href="{% url 'pays:pay'%}">pagamentos</a></li>
                  <li><a class="dropdown-item" href="{% url 'pays:biblioteca'%}">Biblioteca</a></li>
                  <li><a class="dropdown-item" href="{% url 'pays:prof'%}">professores</a></li>
              </ul>
          </li>
          <!--<li class="nav-item">
              <a class="nav-link active" href="{% url 'pays:pay'%}"> Pagamentos</a>
          </li>-->
          {% else %}
          <li class="nav-item">
              <a class="nav-link active" href="../../accounts/login" > login</a>
          </li>
          {% endif %}
          <li class="nav-item">
              <a class="nav-link active" href="{% url 'pays:info'%}"> Info</a>
          </li>

          <li class="nav-item">
              <a class="nav-link active" href="{% url 'pays:inscricoes'%}">Inscrições</a>
          </li>
          {% if user.is_authenticated%}
          <li class="nav-item">
              <a class="nav-link active" href="../../accounts/logout" > logout</a>
          </li>
          {% endif%}
      </ul>
    </div>
  </div>
</nav>
</div>

{% block content%}{% endblock content%}
<script src="https:/8/cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/js/bootstrap.bundle.min.js" integrity="sha384-ygbV9kiqUc6oa4msXn9868pTtWMgiQaeYH7/t7LECLbyPA2x65Kgf80OJFdroafW" crossorigin="anonymous"></script>
<!-- JavaScript Bundle with Popper -->
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/js/bootstrap.bundle.min.js" integrity="sha384-b5kHyXgcpbZJO/tY9Ul7kGkf1S0CWuKcCD38l8YkeH8z8QjE0GmW1gYU5S9FOnJ0" crossorigin="anonymous"></script>
</body>
</html>

pays/templates/pays/biblioteca.html
{% extends 'pays/base.html'%}
{% load static%}

{% block content%}
<h1 class="titulo">Escola</h1>
<h2 class="titulo">Horários para o ano 2021</h2>

<div class="offset-1 col-10">
    <a class="btn btn-primary btn-block lista" href="https://drive.google.com/drive/folders/157Fi4lQPeuMJvWSGs8VhxFYP4I6A5R_O?usp=sharing">curso de informática</a>
    <a class="btn btn-primary btn-block lista" href="https://drive.google.com/drive/folders/1P0onnWZoDSg1y_jT6i5dj5qYpfnVg0jV?usp=sharing">curso de medicina</a>
    <a class="btn btn-primary btn-block lista" href="https://drive.google.com/drive/folders/1b9X_Iho0YnTiXTBOV2BKjInkY0ypJJDN?usp=sharing">curso de electrónica</a>
</div>
{% endblock content%}

pays/templates/pays/comentario.html
{% extends 'pays/base.html'%}
{% load crispy_forms_tags%}
{% block content%}
<div class="offset-1 col-10">
    <form action="." method="post">
        {% csrf_token%}
        {{form|crispy}}
        <button name='submit' class="btn btn-primary btn-block" >Enviar</button>
    </form>
</div>
{% endblock content%}

pays/templates/pays/confirmar.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>

<body>
   {% extends 'pays/base.html'%}
   {% block content %}
   <div class="offset-1 col-10">
   <h1>Confirmar o pagamento da mensalidade</h1>
   <br>
   <br><br><br>
   </div>
   <div class="offset-1 col-10" id="paypal-button-container"></div>

    <!-- Include the PayPal JavaScript SDK -->
    <script src="https://www.paypal.com/sdk/js?client-id=Ab7i5SEXtQpPpJwtClI_bV6SrETyUX_WFk633idTc1k7q0rz6NdfCq1C6VVcMTlnMB4nNJIiV-zIhGqy&currency=USD"></script>

    <script>

    var total = '{{pagar}}'

    var productId = '{{pagar.id}}'

        // Render the PayPal button into #paypal-button-container
        paypal.Buttons({

            // Set up the transaction
            createOrder: function(data, actions) {
                return actions.order.create({
                    purchase_units: [{
                        amount: {
                            value: total
                        }
                    }]
                });
            },

            // Finalize the transaction
            onApprove: function(data, actions) {
                return actions.order.capture().then(function(details) {
                    // Show a success message to the buyer
                    alert('Transaction completed by ' + details.payer.name.given_name + '!');
                });
            }


        }).render('#paypal-button-container');
    </script>
   {% endblock content%}
</body>
</html>

pays/templates/pays/email.html
ola mundo

pays/templates/pays/hor.html
{% extends 'pays/base.html'%}
{% load static%}

{% block content%}
<h1 class="titulo">Escola</h1>
<h2 class="titulo">Horários para o ano 2021</h2>

<div class="offset-1 col-10">
    <a class="btn btn-primary btn-block lista" href="https://drive.google.com/file/d/13ygGHo-mdR3TO0f_R1AYqvZvgN1MeHBU/view?usp=sharing">1 classe</a>
    <a class="btn btn-primary btn-block lista" href="https://drive.google.com/file/d/13ygGHo-mdR3TO0f_R1AYqvZvgN1MeHBU/view?usp=sharing">2 classe</a>
    <a class="btn btn-primary btn-block lista" href="https://drive.google.com/file/d/13ygGHo-mdR3TO0f_R1AYqvZvgN1MeHBU/view?usp=sharing">3 classe</a>
    <a class="btn btn-primary btn-block lista" href="https://drive.google.com/file/d/13ygGHo-mdR3TO0f_R1AYqvZvgN1MeHBU/view?usp=sharing">4 classe</a>
    <a class="btn btn-primary btn-block lista" href="https://drive.google.com/file/d/13ygGHo-mdR3TO0f_R1AYqvZvgN1MeHBU/view?usp=sharing">5 classe</a>
    <a class="btn btn-primary btn-block lista" href="https://drive.google.com/file/d/13ygGHo-mdR3TO0f_R1AYqvZvgN1MeHBU/view?usp=sharing">6 classe</a>
    <a class="btn btn-primary btn-block lista" href="https://drive.google.com/file/d/13ygGHo-mdR3TO0f_R1AYqvZvgN1MeHBU/view?usp=sharing">7 classe</a>
    <a class="btn btn-primary btn-block lista" href="https://drive.google.com/file/d/13ygGHo-mdR3TO0f_R1AYqvZvgN1MeHBU/view?usp=sharing">8 classe</a>
    <a class="btn btn-primary btn-block lista" href="https://drive.google.com/file/d/13ygGHo-mdR3TO0f_R1AYqvZvgN1MeHBU/view?usp=sharing">9 classe</a>
    <a class="btn btn-primary btn-block lista" href="https://drive.google.com/file/d/13ygGHo-mdR3TO0f_R1AYqvZvgN1MeHBU/view?usp=sharing">10 classe</a>

</div>
{% endblock content%}

pays/templates/pays/index.html
{% extends 'pays/base.html'%}
{% load static%}

{% block content%}
<div class="offset-1 col-10">
    <img src="{% static 'images/5.jpg'%}" class="img-fluid">
    <h1 class="titulo">Escola</h1>
    <p>Este sistema foi criado com intuito de diminuir o contacto entre as pessoas na escola. Facilitando assim os pagamentos das mensalidades, as renovacoes das matriculas, a verificacao de pautas, a convocacao de encaregados</p>
    <p>Tudo isso para um bem maior que e' evitar a propagacao do corona virus.</p>

    <p>Esperamos que este sistema seja recebido com as duas maos, obrigado.</p>
    <i>#FicaEmCasa</i>
</div>
{% endblock content%}

pays/templates/pays/info.html
{% extends 'pays/base.html'%}

{% block content%}
<div class="content fluid">
<div class="offset-1 col-10">
  <h2>Tabela de pagamentos</h2>
  <table class="table" id="tabelaspec">
    <tr><td class="ce">Classe</td><td class="cd">Valor</td></tr>
    <tr><td class="ce">1</td><td class="cd">100mt</td></tr>
    <tr><td class="ce">2</td><td class="cd">200mt</td></tr>
    <tr><td class="ce">3</td><td class="cd">300mt</td></tr>
    <tr><td class="ce">4</td><td class="cd">400mt</td></tr>
    <tr><td class="ce">5</td><td class="cd">500mt</td></tr>
    <tr><td class="ce">6</td><td class="cd">600mt</td></tr>
    <tr><td class="ce">7</td><td class="cd">700mt</td></tr>
    <tr><td class="ce">8</td><td class="cd">800mt</td></tr>
    <tr><td class="ce">9</td><td class="cd">900mt</td></tr>
    <tr><td class="ce">10</td><td class="cd">1000mt</td></tr>
    <tr><td class="ce">11</td><td class="cd">1100mt</td></tr>
  </table>
  <h2>Mais informacoes</h2>

  <p>Com o avanco tecnonologico da escola, brevemente as matriculas serao feitas apartir deste site via online.</p>
  <p>Nao so matriculas serao feitas via online, Mas tambem a convocacao de encarregados para reunioes, A verificacao de pautas, As novas turmas.
  A lista dos professores de cada classe e cada turma os horarios, E ate os melhores alunos</p>


  <h2>Como podemos melhorar o site?</h2>
  <p>Adicione o seu comentário:<a href="/comentario/">comentar</a></p>
  <h3>Comentarios</h3>

    {% for com in comentario%}
    <table class="table">
      <tr>
        <td class="ce"><b>{{com.data|date:'M d, Y H:i' }}</b></td>
      </tr>
      <tr>
        <td>{{com}}</td>
      </tr>
    </table>
    {% empty%}
          <p>Não tem comentarios ainda</p>
    {%endfor%}
  </ul>
    </div>
</div>
</div>
{% endblock content%}

pays/templates/pays/inscricoes.html
{% extends 'pays/base.html'%}
{% load crispy_forms_tags%}
{% block content%}
<div class="offset-1 col-10">
    <form action="." method="post">
        <h1>Inscrições</h1>
        {% csrf_token%}
        {{form|crispy}}
        <button name='submit' class="btn btn-primary btn-block" >Enviar</button>
    </form>
</div>
{% endblock content%}

pays/templates/pays/mel.html
{% extends 'pays/base.html'%}
{% load static%}

{% block content%}
<h1 class="titulo">Escola</h1>
<h2 class="titulo">Melhores alunos</h2>

<div class="offset-1 col-10">
    <h3>1 classe</h3>
    <img src="{% static 'images/6.jpg'%}" class="img-fluid">
    <br>
    <h3>2 classe</h3>
    <img src="{% static 'images/7.jpg'%}" class="img-fluid">
    <br>
    <h3>3 classe</h3>
    <img src="{% static 'images/8.jpg'%}" class="img-fluid">
    <br>
    <h3>4 classe</h3>
    <img src="{% static 'images/5.jpg'%}" class="img-fluid">
</div>
{% endblock content%}

pays/templates/pays/pay.html
{% extends 'pays/base.html'%}
{% load crispy_forms_tags%}
{% block content%}
<div class="offset-1 col-10">
    <h1>Fazendo pagamentos</h1>

    {% if messages%}
    <ul class="messages">
        {% for message in messages%}
        <li {% if message.tags%}class="alert alert-{{message.tags}}"{% endif%}>{{message}}</li>
        {% endfor %}
    </ul>
    {% endif %}

    <form action="." method="post">
        {% csrf_token%}
        {{form|crispy}}

        <button name='submit' class="btn btn-primary btn-block">Salvar dados do/a aluno/a
        </button>

        <br>
        <br>
        <div class="offset-1 col-10" id="paypal-button-container"></div>

        <!-- Include the PayPal JavaScript SDK -->
        <script src="https://www.paypal.com/sdk/js?client-id=Ab7i5SEXtQpPpJwtClI_bV6SrETyUX_WFk633idTc1k7q0rz6NdfCq1C6VVcMTlnMB4nNJIiV-zIhGqy&currency=USD"></script>

        <script>
        // Render the PayPal button into #paypal-button-container
        paypal.Buttons({

            // Set up the transaction
            createOrder: function(data, actions) {
                return actions.order.create({
                    purchase_units: [{
                        amount: {
                            value: '0.1'
                        }
                    }]
                });
            },

            // Finalize the transaction
            onApprove: function(data, actions) {
                return actions.order.capture().then(function(details) {
                    // Show a success message to the buyer
                    alert('Mensalidade paga, aguarde pelo recibo no seu e-mail');
                });
            }


        }).render('#paypal-button-container');
    </script>

    </form>
</div>
{% endblock content%}

pays/templates/pays/prof.html
{% extends 'pays/base.html'%}
{% load static%}

{% block content%}
<h1 class="titulo">Escola</h1>
<h2 class="titulo">Professores</h2>

<div class="offset-1 col-10">
    <a class="btn btn-primary btn-block lista" href="#">Joao Tembe</a>
    <a class="btn btn-primary btn-block lista" href="#">Maria Calisto</a>
    <a class="btn btn-primary btn-block lista" href="#">Armando Cesar</a>
    <a class="btn btn-primary btn-block lista" href="#">Roberto changa</a>
    <a class="btn btn-primary btn-block lista" href="#">Lina Rosalina</a>
</div>
{% endblock content%}